#!/usr/bin/env bash

launchctl unload -w /Users/alberto.ramirez/Library/LaunchAgents/org.pfc.aramirez.agent.plist || true
launchctl load -w /Users/alberto.ramirez/Library/LaunchAgents/org.pfc.aramirez.agent.plist

#launchctl submit \
#  -l com.hurpdurp.apps \
#  -o /var/logs/hellonode.info.log \
#  -e /var/logs/hellonode.err.log \
#  -- \
#  /usr/local/bin/node \
#  /opt/HelloNode/bin/server.js